baseurl = "https://resource.gramin.jp/"
DefaultContentLanguage = "ja-jp"
title = "小学生のためのプログラミング教材"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true
disqusShortname = "ぐらみん株式会社が運営している キッズプログラミング教室ぐらみんで授業の時に利用している教材です。"

hasCJKLanguage = true
googleAnalytics = "UA-3918039-22"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
